- alias: "Evaluate Conditions When inverter_input Restarts or Becomes Available & Send Msg"
  trigger:
    - platform: state
      entity_id: switch.sonoff_1001e5d0bf # inverter_input
      from: 'unavailable'
      to: 'on'
    - platform: state
      entity_id: switch.sonoff_1001e5d0bf # inverter_input
      to: 'off'
  action:
    - variables:   # define variable that holds the current datetime
        inverter_available_datetime: "{{ utcnow().strftime('%Y-%m-%d %H:%M:%S') }}" 
    - delay: '00:00:05'  # Wait for 5 seconds to ensure the device is fully online
    - service: script.evaluate_conditions_1
    - service: notify.WhatsApp
      data:
        message: 'The grid power is ON'
    - service: input_datetime.set_datetime
      data:
        entity_id: input_datetime.datetime_when_inverter_input_is_available
        datetime: "{{ inverter_available_datetime }}"

- alias: "Send Msg When inverter_input Becomes Unavailable"
  trigger:
    - platform: state
      entity_id: switch.sonoff_1001e5d0bf  # inverter_input
      to: 'unavailable' 

  action:
    - variables:
        inverter_input_latest_available_datetime: "{{ state_attr('input_datetime.datetime_when_inverter_input_is_available', 'timestamp') | float }}"
        duration: "{{ utcnow().timestamp() - inverter_input_latest_available_datetime }}"
    - service: notify.WhatsApp
      data:
        message: >
          {% set hours = (duration // 3600) | int %}
          {% set minutes = ((duration % 3600) // 60) | int %}
          {% set seconds = (duration % 60) | int %}
          The grid power is OFF. It was available for {{ hours }} hours, {{ minutes }} minutes, and {{ seconds }} seconds.
