
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

sonoff:
  username: !secret username
  password: !secret password
  mode: auto

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

notify:
  - name: WhatsApp
    platform: rest
    resource: https://api.callmebot.com/whatsapp.php
    data:
      source: HA
      phone: !secret my_phone_num     # Replace with your phone number
      apikey: !secret my_api_key      # Replace with your CallMeBot API key
